import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import GlobalLoader from "@/Components/GlobalLoader/GlobalLoader";


const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "ThoughtNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased overflow-x-hidden`}
      >
        <ToastContainer theme="dark" position="top-right" autoClose={3000} />
        <SessionProvider>
          <GlobalLoader />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
